# Generated by Django 2.1 on 2018-11-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion', models.CharField(max_length=10)),
                ('id_mat', models.IntegerField(default=0)),
                ('nom_mat', models.CharField(max_length=50)),
                ('id_int', models.IntegerField(default=0)),
                ('nom_int', models.CharField(max_length=50)),
                ('id_vesp', models.IntegerField(default=0)),
                ('nom_vesp', models.CharField(max_length=50)),
            ],
        ),
    ]
