# Generated by Django 2.1 on 2018-11-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espacio',
            name='nom_int',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='espacio',
            name='nom_mat',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='espacio',
            name='nom_vesp',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
